# Generated by Django 5.0.6 on 2024-06-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=200)),
                ('clocation', models.CharField(max_length=50)),
                ('totalnostudents', models.CharField(max_length=10)),
                ('cdepartment', models.CharField(max_length=200)),
            ],
        ),
    ]
